### ISSUE TITLE
Does not download EE versions

### ISSUE THREAD

**Issue by kerrermanisNL** [gwillem/magento-downloader#3]
Hey Willem! I'm reading around a little in our docs and it mentions that this should download EE versions of magento as well. Is that accurate, because it doesn't at the moment. The URL used to check for versions etc. (https://www.magentocommerce.com/products/downloads/info/json) also only lists a `ce-full` key, not an `ee-full` key. Was that changed and do things need to be updated?

Or if this never downloaded EE versions you can close the issue :)

**Comment by kerrermanisNL** [comment]
Another possibility that something changed with the account I'm using. Seeing if that's the case at the moment. But if someone else could confirm they're also missing the same key, it would be consistent.

**Comment by gwillem** [comment]
As discussed, depends on Magento auth token.
